# Generated by Django 4.2.5 on 2023-09-25 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Header',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='Title')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(max_length=30, verbose_name='Phone Number')),
                ('btn_name', models.CharField(max_length=40, verbose_name='Button Name')),
                ('path1', models.CharField(max_length=40, verbose_name='Path 1')),
                ('path2', models.CharField(max_length=40, verbose_name='Path 2')),
                ('path3', models.CharField(max_length=40, verbose_name='Path 3')),
                ('path4', models.CharField(max_length=40, verbose_name='Path 4')),
                ('path5', models.CharField(max_length=40, verbose_name='Path 5')),
                ('path6', models.CharField(max_length=40, verbose_name='Path 6')),
                ('social1', models.URLField(verbose_name='Social 1')),
                ('social2', models.URLField(verbose_name='Social 2')),
                ('social3', models.URLField(verbose_name='Social 3')),
                ('social4', models.URLField(verbose_name='Social4')),
            ],
            options={
                'verbose_name': 'Header',
                'verbose_name_plural': 'Header',
            },
        ),
    ]
