# Generated by Django 4.2.5 on 2023-09-25 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_homepage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='path',
            field=models.CharField(max_length=30, verbose_name='Path'),
        ),
    ]
