# Generated by Django 4.2.5 on 2023-09-25 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_offer_offercontent'),
    ]

    operations = [
        migrations.AddField(
            model_name='offercontent',
            name='icon',
            field=models.CharField(default=1, max_length=10, verbose_name='Icon'),
            preserve_default=False,
        ),
    ]
