# Generated by Django 4.2.5 on 2023-09-25 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_gallery_testimonial_testimonialtitle'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teachers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='', verbose_name='Image')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('position', models.CharField(max_length=50, verbose_name='Position')),
                ('text1', models.TextField(verbose_name='Text 1')),
                ('social1', models.URLField(verbose_name='Social 1')),
                ('social2', models.URLField(verbose_name='Social 2')),
                ('social3', models.URLField(verbose_name='Social 3')),
                ('social4', models.URLField(verbose_name='Social 4')),
                ('text2', models.TextField(verbose_name='Text 2')),
                ('text3', models.TextField(verbose_name='Text 3')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(max_length=30, verbose_name='Phone Number')),
                ('experience', models.IntegerField(verbose_name='Experience')),
            ],
            options={
                'verbose_name': 'Teachers',
                'verbose_name_plural': 'Teachers',
            },
        ),
        migrations.AlterModelOptions(
            name='gallery',
            options={'verbose_name': 'Gallery', 'verbose_name_plural': 'Gallery'},
        ),
    ]
