# Generated by Django 4.2.5 on 2023-09-26 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_remove_courses_slug'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Courses',
        ),
    ]
