# Generated by Django 4.2.5 on 2023-09-27 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_courses'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(max_length=10, verbose_name='Icon')),
                ('info', models.CharField(max_length=50, verbose_name='Info')),
            ],
        ),
    ]
