# Generated by Django 4.2.5 on 2023-09-27 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_registration'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='registration',
            options={'verbose_name': 'Registration', 'verbose_name_plural': 'Registration'},
        ),
    ]
